{% set name = "apstools" %}
{% set version = "1.6.3rc4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apstools-{{ version }}.tar.gz
  sha256: c95338c7b7a33c5e209da4cc0addd775b5d2fe2a39699c847259ff7a6a706471

build:
  entry_points:
    - bluesky_snapshot = apstools.snapshot.application:snapshot_cli
    - bluesky_snapshot_viewer = apstools.snapshot.application:snapshot_gui
    - spec2ophyd = apstools.migration.spec2ophyd:main
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<38 and py>310]
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - python
    - area-detector-handlers
    - bluesky >=1.6.7
    - databroker =1.2
    - databroker-pack
    - furo
    - h5py
    - intake
    - mongoquery >=1.3.6
    - numpy
    - openpyxl
    - ophyd >=1.6.1
    - pandas
    - pint
    - pip
    - prompt-toolkit
    - pyepics >=3.4.3
    - pymongo
    - pyqt =5
    - pyRestTable
    - qt =5
    - readline !=8.1.2
    - spec2nexus
    - sphinx >=5
    - xlrd
    - xorg-libx11

test:
  imports:
    - apstools
  commands:
    - pip check
    - bluesky_snapshot --help
    # - bluesky_snapshot_viewer --help
    - spec2ophyd --help
  requires:
    - pip

about:
  home: https://bcda-aps.github.io/apstools/
  summary: Various Python tools for use with the Bluesky Framework at the APS
  license: BSD-4-Clause
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - prjemian
