{% set name = "apstools" %}
{% set version = "1.6.19rc3" %}
{% set sha256 = "5560a34de4e756ae1ea2f6022d95081e1d817127517d5654f11a1fa65b1ae6d2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  entry_points:
    - spec2ophyd = apstools.migration.spec2ophyd:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8, <=3.11
    - setuptools-scm >=8.0
    - setuptools >=64
    - pip
  run:
    - python >=3.8, <=3.11
    - area-detector-handlers
    - bluesky >=1.6.7, !=1.11.0
    - bluesky-live
    - databroker =1.2.5
    - databroker-pack
    - entrypoints
    - h5py
    - intake <=1
    - matplotlib-base
    - mongoquery >=1.3.6
    - numpy
    - openpyxl
    - ophyd >=1.6.1
    - pint
    - pip
    - psutil
    - pyepics >=3.4.2
    - pyRestTable >=2020.0.8
    - pysumreg
    # - readline !=8.1.2
    - scipy
    - spec2nexus >=2021.1.7
    - toolz >=0.12.1
    - xlrd

test:
  commands:
    - pip check
    - spec2ophyd --help
  # imports:
  #   - apstools
  #   - apstools.callbacks
  #   - apstools.devices
  #   - apstools.plans
  #   - apstools.synApps
  #   - apstools.utils
  requires:
    - conda-verify
    - pip

about:
  home: https://bcda-aps.github.io/apstools/latest/
  summary: Various Python tools for use with the Bluesky Framework at the APS
  license: BSD-4-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - prjemian
