{% set name = "apstools" %}
{% set version = "1.6.5rc5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apstools-{{ version }}.tar.gz
  sha256: bf5993d8a81f166bcc63c3c1cfcffd2cb44cb49a878994f061386d642fb143d5

build:
  entry_points:
    # - bluesky_snapshot = apstools.snapshot.application:snapshot_cli
    # - bluesky_snapshot_viewer = apstools.snapshot.application:snapshot_gui
    - spec2ophyd = apstools.migration.spec2ophyd:main
  # per https://github.com/pypa/setuptools_scm/issues/357#issuecomment-846476165
  # SETUPTOOLS_SCM_PRETEND_VERSION="$(python3 setup.py --version)" pip install .
  script: SETUPTOOLS_SCM_DEBUG=1 SETUPTOOLS_SCM_PRETEND_VERSION="$(python3 setup.py --version)" {{ PYTHON }} -m pip install . -vv
  # skip: true  # [py<38 and py>310]
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - setuptools-scm
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - area-detector-handlers
    - bluesky >=1.6.7
    - databroker =1.2
    - databroker-pack
    - h5py
    - intake
    - mongoquery >=1.3.6
    - numpy
    - openpyxl
    - ophyd >=1.6.1
    - pandas
    - pint
    - pip
    - prompt-toolkit
    - pyepics >=3.4.3
    - pymongo
    - pyqt =5
    - pyRestTable
    - qt =5
    - readline !=8.1.2
    - spec2nexus
    - sphinx >=5
    - xlrd
    - xorg-libx11

test:
  imports:
    - apstools
  commands:
    - pip check
    # - bluesky_snapshot --help
    # - bluesky_snapshot_viewer --help
    - spec2ophyd --help
  requires:
    - pip

about:
  home: https://bcda-aps.github.io/apstools/
  summary: Various Python tools for use with the Bluesky Framework at the APS
  license: BSD-4-Clause
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - prjemian
