{% set name = "apstools" %}
{% set version = "1.7.4rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: "c1004bb0b3f9a7b2ff0b506c4efab82ea5990154ef9621a36db4ae514c29f94d"

build:
  entry_points:
    - spec2ophyd = apstools.migration.spec2ophyd:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm >=8.0
    - setuptools >=77
    - pip
  run:
    - python >={{ python_min }}
    - area-detector-handlers
    - bluesky >=1.6.7, !=1.11.0
    - bluesky-live
    - databroker <=1.999
    - databroker-pack
    - deprecated
    - entrypoints
    - h5py
    - intake <=1
    - matplotlib-base
    - mongoquery >=1.3.6
    - numpy  # ?? >=2
    - openpyxl
    - ophyd >=1.6.1
    - pandas
    - pint
    - pip
    - psutil
    - pyepics >=3.4.3
    - pyRestTable >=2020.0.8
    - pysumreg
    - scipy
    - spec2nexus >=2021.1.7
    - toolz >=0.12.1
    - xlrd

test:
  commands:
    # - pip check
    - spec2ophyd --help
    - spec2ophyd --version
  imports:
    - apstools
    - apstools.callbacks
    - apstools.devices
    - apstools.plans
    - apstools.synApps
    - apstools.utils
  requires:
    - pip
    - conda-verify
    - python {{ python_min }}

about:
  home: https://bcda-aps.github.io/apstools/latest/
  summary: Various Python tools for use with the Bluesky Framework at the APS
  license: LicenseRef-ANL-Open-Source-License
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - prjemian
